In [2]:
import pandas as pd
import glob
import os
import numpy as np

In [3]:
search_path = "../data/*.csv" 
all_files = glob.glob(search_path, recursive=True)
processed_dfs = []
raster_files = [f for f in all_files if "raster_data" in f.lower()]

print(f"Found {len(raster_files)} files.")

Found 193 files.

In [31]:
processed_dfs = []
for filename in raster_files:
    df = pd.read_csv(filename) 
    site_id = filename.split('site')[1].replace('.csv', '')
    df.insert(0, 'site', site_id)
    processed_dfs.append(df)

data = pd.concat(processed_dfs, axis=0, ignore_index=True)
data.to_csv("data/data.csv", index=False)

In [4]:
data=pd.read_csv('../data/data.csv')
data.describe()

,site,labels.stimID,labels.person,time.1_2,time.2_3,time.3_4,time.4_5,time.5_6,time.6_7,time.7_8,...,time.791_792,time.792_793,time.793_794,time.794_795,time.795_796,time.796_797,time.797_798,time.798_799,time.799_800,time.800_801
count,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,...,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000,206216.000000
mean,174.153887,100.592219,12.930374,0.004418,0.004520,0.003967,0.004020,0.004389,0.004166,0.003860,...,0.005291,0.005363,0.005140,0.005358,0.005257,0.004966,0.005140,0.005019,0.005150,0.004932
std,100.650524,57.703535,7.177461,0.066319,0.067076,0.062857,0.063276,0.066101,0.064407,0.062009,...,0.072544,0.073038,0.071511,0.073005,0.072312,0.070292,0.071511,0.070667,0.071578,0.070053
min,5.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,105.000000,51.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,162.000000,101.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,222.000000,151.000000,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,437.000000,200.000000,25.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
data

,site,site_info.monkey,site_info.region,labels.stimID,labels.person,labels.orientation,labels.orient_person_combo,time.1_2,time.2_3,time.3_4,...,time.791_792,time.792_793,time.793_794,time.794_795,time.795_796,time.796_797,time.797_798,time.798_799,time.799_800,time.800_801
0,13,bert,am,1,1,front,front 1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,13,bert,am,1,1,front,front 1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,13,bert,am,1,1,front,front 1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,13,bert,am,2,2,front,front 2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13,bert,am,2,2,front,front 2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206211,225,lupo,am,200,25,back,back 25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206212,225,lupo,am,200,25,back,back 25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206213,225,lupo,am,200,25,back,back 25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206214,225,lupo,am,200,25,back,back 25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206215,225,lupo,am,200,25,back,back 25,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
print([i for i in data.columns])

['site', 'site_info.monkey', 'site_info.region', 'labels.stimID', 'labels.person', 'labels.orientation', 'labels.orient_person_combo', 'time.1_2', 'time.2_3', 'time.3_4', 'time.4_5', 'time.5_6', 'time.6_7', 'time.7_8', 'time.8_9', 'time.9_10', 'time.10_11', 'time.11_12', 'time.12_13', 'time.13_14', 'time.14_15', 'time.15_16', 'time.16_17', 'time.17_18', 'time.18_19', 'time.19_20', 'time.20_21', 'time.21_22', 'time.22_23', 'time.23_24', 'time.24_25', 'time.25_26', 'time.26_27', 'time.27_28', 'time.28_29', 'time.29_30', 'time.30_31', 'time.31_32', 'time.32_33', 'time.33_34', 'time.34_35', 'time.35_36', 'time.36_37', 'time.37_38', 'time.38_39', 'time.39_40', 'time.40_41', 'time.41_42', 'time.42_43', 'time.43_44', 'time.44_45', 'time.45_46', 'time.46_47', 'time.47_48', 'time.48_49', 'time.49_50', 'time.50_51', 'time.51_52', 'time.52_53', 'time.53_54', 'time.54_55', 'time.55_56', 'time.56_57', 'time.57_58', 'time.58_59', 'time.59_60', 'time.60_61', 'time.61_62', 'time.62_63', 'time.63_64', 'time.64_65', 'time.65_66', 'time.66_67', 'time.67_68', 'time.68_69', 'time.69_70', 'time.70_71', 'time.71_72', 'time.72_73', 'time.73_74', 'time.74_75', 'time.75_76', 'time.76_77', 'time.77_78', 'time.78_79', 'time.79_80', 'time.80_81', 'time.81_82', 'time.82_83', 'time.83_84', 'time.84_85', 'time.85_86', 'time.86_87', 'time.87_88', 'time.88_89', 'time.89_90', 'time.90_91', 'time.91_92', 'time.92_93', 'time.93_94', 'time.94_95', 'time.95_96', 'time.96_97', 'time.97_98', 'time.98_99', 'time.99_100', 'time.100_101', 'time.101_102', 'time.102_103', 'time.103_104', 'time.104_105', 'time.105_106', 'time.106_107', 'time.107_108', 'time.108_109', 'time.109_110', 'time.110_111', 'time.111_112', 'time.112_113', 'time.113_114', 'time.114_115', 'time.115_116', 'time.116_117', 'time.117_118', 'time.118_119', 'time.119_120', 'time.120_121', 'time.121_122', 'time.122_123', 'time.123_124', 'time.124_125', 'time.125_126', 'time.126_127', 'time.127_128', 'time.128_129', 'time.129_130', 'time.130_131', 'time.131_132', 'time.132_133', 'time.133_134', 'time.134_135', 'time.135_136', 'time.136_137', 'time.137_138', 'time.138_139', 'time.139_140', 'time.140_141', 'time.141_142', 'time.142_143', 'time.143_144', 'time.144_145', 'time.145_146', 'time.146_147', 'time.147_148', 'time.148_149', 'time.149_150', 'time.150_151', 'time.151_152', 'time.152_153', 'time.153_154', 'time.154_155', 'time.155_156', 'time.156_157', 'time.157_158', 'time.158_159', 'time.159_160', 'time.160_161', 'time.161_162', 'time.162_163', 'time.163_164', 'time.164_165', 'time.165_166', 'time.166_167', 'time.167_168', 'time.168_169', 'time.169_170', 'time.170_171', 'time.171_172', 'time.172_173', 'time.173_174', 'time.174_175', 'time.175_176', 'time.176_177', 'time.177_178', 'time.178_179', 'time.179_180', 'time.180_181', 'time.181_182', 'time.182_183', 'time.183_184', 'time.184_185', 'time.185_186', 'time.186_187', 'time.187_188', 'time.188_189', 'time.189_190', 'time.190_191', 'time.191_192', 'time.192_193', 'time.193_194', 'time.194_195', 'time.195_196', 'time.196_197', 'time.197_198', 'time.198_199', 'time.199_200', 'time.200_201', 'time.201_202', 'time.202_203', 'time.203_204', 'time.204_205', 'time.205_206', 'time.206_207', 'time.207_208', 'time.208_209', 'time.209_210', 'time.210_211', 'time.211_212', 'time.212_213', 'time.213_214', 'time.214_215', 'time.215_216', 'time.216_217', 'time.217_218', 'time.218_219', 'time.219_220', 'time.220_221', 'time.221_222', 'time.222_223', 'time.223_224', 'time.224_225', 'time.225_226', 'time.226_227', 'time.227_228', 'time.228_229', 'time.229_230', 'time.230_231', 'time.231_232', 'time.232_233', 'time.233_234', 'time.234_235', 'time.235_236', 'time.236_237', 'time.237_238', 'time.238_239', 'time.239_240', 'time.240_241', 'time.241_242', 'time.242_243', 'time.243_244', 'time.244_245', 'time.245_246', 'time.246_247', 'time.247_248', 'time.248_249', 'time.249_250', 'time.250_251', 'time.251_252', 'time.252_253', 'time.253_254', 'time.254_255', 'time.255_256', 'time.256_257', 'time.257_258', 'time.258_259', 'time.259_260', 'time.260_261', 'time.261_262', 'time.262_263', 'time.263_264', 'time.264_265', 'time.265_266', 'time.266_267', 'time.267_268', 'time.268_269', 'time.269_270', 'time.270_271', 'time.271_272', 'time.272_273', 'time.273_274', 'time.274_275', 'time.275_276', 'time.276_277', 'time.277_278', 'time.278_279', 'time.279_280', 'time.280_281', 'time.281_282', 'time.282_283', 'time.283_284', 'time.284_285', 'time.285_286', 'time.286_287', 'time.287_288', 'time.288_289', 'time.289_290', 'time.290_291', 'time.291_292', 'time.292_293', 'time.293_294', 'time.294_295', 'time.295_296', 'time.296_297', 'time.297_298', 'time.298_299', 'time.299_300', 'time.300_301', 'time.301_302', 'time.302_303', 'time.303_304', 'time.304_305', 'time.305_306', 'time.306_307', 'time.307_308', 'time.308_309', 'time.309_310', 'time.310_311', 'time.311_312', 'time.312_313', 'time.313_314', 'time.314_315', 'time.315_316', 'time.316_317', 'time.317_318', 'time.318_319', 'time.319_320', 'time.320_321', 'time.321_322', 'time.322_323', 'time.323_324', 'time.324_325', 'time.325_326', 'time.326_327', 'time.327_328', 'time.328_329', 'time.329_330', 'time.330_331', 'time.331_332', 'time.332_333', 'time.333_334', 'time.334_335', 'time.335_336', 'time.336_337', 'time.337_338', 'time.338_339', 'time.339_340', 'time.340_341', 'time.341_342', 'time.342_343', 'time.343_344', 'time.344_345', 'time.345_346', 'time.346_347', 'time.347_348', 'time.348_349', 'time.349_350', 'time.350_351', 'time.351_352', 'time.352_353', 'time.353_354', 'time.354_355', 'time.355_356', 'time.356_357', 'time.357_358', 'time.358_359', 'time.359_360', 'time.360_361', 'time.361_362', 'time.362_363', 'time.363_364', 'time.364_365', 'time.365_366', 'time.366_367', 'time.367_368', 'time.368_369', 'time.369_370', 'time.370_371', 'time.371_372', 'time.372_373', 'time.373_374', 'time.374_375', 'time.375_376', 'time.376_377', 'time.377_378', 'time.378_379', 'time.379_380', 'time.380_381', 'time.381_382', 'time.382_383', 'time.383_384', 'time.384_385', 'time.385_386', 'time.386_387', 'time.387_388', 'time.388_389', 'time.389_390', 'time.390_391', 'time.391_392', 'time.392_393', 'time.393_394', 'time.394_395', 'time.395_396', 'time.396_397', 'time.397_398', 'time.398_399', 'time.399_400', 'time.400_401', 'time.401_402', 'time.402_403', 'time.403_404', 'time.404_405', 'time.405_406', 'time.406_407', 'time.407_408', 'time.408_409', 'time.409_410', 'time.410_411', 'time.411_412', 'time.412_413', 'time.413_414', 'time.414_415', 'time.415_416', 'time.416_417', 'time.417_418', 'time.418_419', 'time.419_420', 'time.420_421', 'time.421_422', 'time.422_423', 'time.423_424', 'time.424_425', 'time.425_426', 'time.426_427', 'time.427_428', 'time.428_429', 'time.429_430', 'time.430_431', 'time.431_432', 'time.432_433', 'time.433_434', 'time.434_435', 'time.435_436', 'time.436_437', 'time.437_438', 'time.438_439', 'time.439_440', 'time.440_441', 'time.441_442', 'time.442_443', 'time.443_444', 'time.444_445', 'time.445_446', 'time.446_447', 'time.447_448', 'time.448_449', 'time.449_450', 'time.450_451', 'time.451_452', 'time.452_453', 'time.453_454', 'time.454_455', 'time.455_456', 'time.456_457', 'time.457_458', 'time.458_459', 'time.459_460', 'time.460_461', 'time.461_462', 'time.462_463', 'time.463_464', 'time.464_465', 'time.465_466', 'time.466_467', 'time.467_468', 'time.468_469', 'time.469_470', 'time.470_471', 'time.471_472', 'time.472_473', 'time.473_474', 'time.474_475', 'time.475_476', 'time.476_477', 'time.477_478', 'time.478_479', 'time.479_480', 'time.480_481', 'time.481_482', 'time.482_483', 'time.483_484', 'time.484_485', 'time.485_486', 'time.486_487', 'time.487_488', 'time.488_489', 'time.489_490', 'time.490_491', 'time.491_492', 'time.492_493', 'time.493_494', 'time.494_495', 'time.495_496', 'time.496_497', 'time.497_498', 'time.498_499', 'time.499_500', 'time.500_501', 'time.501_502', 'time.502_503', 'time.503_504', 'time.504_505', 'time.505_506', 'time.506_507', 'time.507_508', 'time.508_509', 'time.509_510', 'time.510_511', 'time.511_512', 'time.512_513', 'time.513_514', 'time.514_515', 'time.515_516', 'time.516_517', 'time.517_518', 'time.518_519', 'time.519_520', 'time.520_521', 'time.521_522', 'time.522_523', 'time.523_524', 'time.524_525', 'time.525_526', 'time.526_527', 'time.527_528', 'time.528_529', 'time.529_530', 'time.530_531', 'time.531_532', 'time.532_533', 'time.533_534', 'time.534_535', 'time.535_536', 'time.536_537', 'time.537_538', 'time.538_539', 'time.539_540', 'time.540_541', 'time.541_542', 'time.542_543', 'time.543_544', 'time.544_545', 'time.545_546', 'time.546_547', 'time.547_548', 'time.548_549', 'time.549_550', 'time.550_551', 'time.551_552', 'time.552_553', 'time.553_554', 'time.554_555', 'time.555_556', 'time.556_557', 'time.557_558', 'time.558_559', 'time.559_560', 'time.560_561', 'time.561_562', 'time.562_563', 'time.563_564', 'time.564_565', 'time.565_566', 'time.566_567', 'time.567_568', 'time.568_569', 'time.569_570', 'time.570_571', 'time.571_572', 'time.572_573', 'time.573_574', 'time.574_575', 'time.575_576', 'time.576_577', 'time.577_578', 'time.578_579', 'time.579_580', 'time.580_581', 'time.581_582', 'time.582_583', 'time.583_584', 'time.584_585', 'time.585_586', 'time.586_587', 'time.587_588', 'time.588_589', 'time.589_590', 'time.590_591', 'time.591_592', 'time.592_593', 'time.593_594', 'time.594_595', 'time.595_596', 'time.596_597', 'time.597_598', 'time.598_599', 'time.599_600', 'time.600_601', 'time.601_602', 'time.602_603', 'time.603_604', 'time.604_605', 'time.605_606', 'time.606_607', 'time.607_608', 'time.608_609', 'time.609_610', 'time.610_611', 'time.611_612', 'time.612_613', 'time.613_614', 'time.614_615', 'time.615_616', 'time.616_617', 'time.617_618', 'time.618_619', 'time.619_620', 'time.620_621', 'time.621_622', 'time.622_623', 'time.623_624', 'time.624_625', 'time.625_626', 'time.626_627', 'time.627_628', 'time.628_629', 'time.629_630', 'time.630_631', 'time.631_632', 'time.632_633', 'time.633_634', 'time.634_635', 'time.635_636', 'time.636_637', 'time.637_638', 'time.638_639', 'time.639_640', 'time.640_641', 'time.641_642', 'time.642_643', 'time.643_644', 'time.644_645', 'time.645_646', 'time.646_647', 'time.647_648', 'time.648_649', 'time.649_650', 'time.650_651', 'time.651_652', 'time.652_653', 'time.653_654', 'time.654_655', 'time.655_656', 'time.656_657', 'time.657_658', 'time.658_659', 'time.659_660', 'time.660_661', 'time.661_662', 'time.662_663', 'time.663_664', 'time.664_665', 'time.665_666', 'time.666_667', 'time.667_668', 'time.668_669', 'time.669_670', 'time.670_671', 'time.671_672', 'time.672_673', 'time.673_674', 'time.674_675', 'time.675_676', 'time.676_677', 'time.677_678', 'time.678_679', 'time.679_680', 'time.680_681', 'time.681_682', 'time.682_683', 'time.683_684', 'time.684_685', 'time.685_686', 'time.686_687', 'time.687_688', 'time.688_689', 'time.689_690', 'time.690_691', 'time.691_692', 'time.692_693', 'time.693_694', 'time.694_695', 'time.695_696', 'time.696_697', 'time.697_698', 'time.698_699', 'time.699_700', 'time.700_701', 'time.701_702', 'time.702_703', 'time.703_704', 'time.704_705', 'time.705_706', 'time.706_707', 'time.707_708', 'time.708_709', 'time.709_710', 'time.710_711', 'time.711_712', 'time.712_713', 'time.713_714', 'time.714_715', 'time.715_716', 'time.716_717', 'time.717_718', 'time.718_719', 'time.719_720', 'time.720_721', 'time.721_722', 'time.722_723', 'time.723_724', 'time.724_725', 'time.725_726', 'time.726_727', 'time.727_728', 'time.728_729', 'time.729_730', 'time.730_731', 'time.731_732', 'time.732_733', 'time.733_734', 'time.734_735', 'time.735_736', 'time.736_737', 'time.737_738', 'time.738_739', 'time.739_740', 'time.740_741', 'time.741_742', 'time.742_743', 'time.743_744', 'time.744_745', 'time.745_746', 'time.746_747', 'time.747_748', 'time.748_749', 'time.749_750', 'time.750_751', 'time.751_752', 'time.752_753', 'time.753_754', 'time.754_755', 'time.755_756', 'time.756_757', 'time.757_758', 'time.758_759', 'time.759_760', 'time.760_761', 'time.761_762', 'time.762_763', 'time.763_764', 'time.764_765', 'time.765_766', 'time.766_767', 'time.767_768', 'time.768_769', 'time.769_770', 'time.770_771', 'time.771_772', 'time.772_773', 'time.773_774', 'time.774_775', 'time.775_776', 'time.776_777', 'time.777_778', 'time.778_779', 'time.779_780', 'time.780_781', 'time.781_782', 'time.782_783', 'time.783_784', 'time.784_785', 'time.785_786', 'time.786_787', 'time.787_788', 'time.788_789', 'time.789_790', 'time.790_791', 'time.791_792', 'time.792_793', 'time.793_794', 'time.794_795', 'time.795_796', 'time.796_797', 'time.797_798', 'time.798_799', 'time.799_800', 'time.800_801']